### ISSUE TITLE
Guidance on what to do when your package is approved

### ISSUE THREAD

**Issue by Rekyt** [ropensci/dev_guide#150]
~~[`rromeo`](https://github.com/ropensci/rromeo) got approved recently by rOpenSci.
I noticed @sckott [mentioned](https://github.com/ropensci/software-review/issues/285#issuecomment-487669241) a couple of things to do once the package is approved.
In brief he mentioned transferring the repository and change the various links
It could be a useful thing to have somewhere in the development guide.~~
Woops, I just realized these comments were available in the "Approval comments template" Appendix. So maybe put them in a separate section "What to do when you package got approved by rOpenSci"?

I also struggled a little bit to change AppVeyor CI and didn't know what should be considered the best practice: should AppVeyor App be installed for the whole rOpenSci group? 
As I was unsure, I enabled OAuth for AppVeyor to my whole GitHub account giving thus access to community organizations. And that let me create a new project using the transferred repo.

**Comment by maelle** [comment]
:wave: @Rekyt!

* Reg Appveyor the guidance is currently in the CI chapter https://ropensci.github.io/dev_guide/ci.html#appveyor-ci-windows and in the template https://ropensci.github.io/dev_guide/approvaltemplate.html (but I think @sckott has used a slightly outdated version :wink:)

* The whole 3d section is about stuff after transfer https://ropensci.github.io/dev_guide/collaboration.html

I don't think having the checklist in an actual chapter would be useful since the maintainers get the checklist via the editor in the submission issue but I am open to suggestions on how to make things such as CI transfer clearer.

**Comment by Rekyt** [comment]
Thank you so much @maelle! Then I just need careful reading :eyes: as everything is already out there...

**Comment by maelle** [comment]
But really your advice as "naive reader" (as opposed to us who've worked on this guide) is super helpful so do not hesitate to give further suggestions and feedback, we want the guide to help maintainers!

**Comment by sckott** [comment]
thanks for the feedback @Rekyt
