### ISSUE TITLE
Appendices B-D are not being rendered properly in the pdf version of the book

### ISSUE THREAD

**Issue by IndrajeetPatil** [ropensci/dev_guide#179]
Maybe these pages can be reformatted somehow to be more pdf-friendly?

![image](https://user-images.githubusercontent.com/11330453/59526247-7a5ad800-8ea6-11e9-8520-32101da028f3.png)

**Comment by noamross** [comment]
I think the easiest thing to do with these is maybe wrap the text in the templates to 80 characters? Ideally there would be  a way to do this for just the PDF (perhaps a pre-processing step), because when actually copy-pasting this into GitHub the line breaks are likely to result in more formatting snafus.
