### ISSUE TITLE
Add a recommendation of pkgdown mode?

### ISSUE THREAD

**Issue by maelle** [ropensci/dev_guide#200]
Cf https://pkgdown.r-lib.org/reference/build_site.html?q=mode#development-mode

Should we recommend the use of `auto`?

@jeroen (and anyone else reading this) any opinion?

**Comment by Bisaloo** [comment]
https://github.com/ropensci/lightr/issues/13#issuecomment-563288452

My understanding is that `auto` is not recommended (at the moment at least)

**Comment by maelle** [comment]
Ah, right, thanks.

@jeroen Is there any plan to allow package authors to have one website for the release version and one for the dev version?

I like the idea, but I'm also wondering how intuitive it is for users at the moment to go from one to the other (from the dev docs to the released docs).

**Comment by jeroen** [comment]
No there are no such plans. Having multiple sites per package really complicates the build and deployment system, and I'm not sure if it makes sense to support this right now. Personally I also think it's a bad idea in the first place because most users might arrive on the site via Google and may not be aware that there are multiple sites and  and how to get to the one they need.

Perhaps in the future we plan to archive old versions of packages and binaries so we could also consider archiving older versions of the docs somehow.

**Comment by maelle** [comment]
Okay, it makes sense.

Now, how do we make it clear the website is for the dev version? Or is the version badge enough? I'm wondering whether users could be surprised if the dev version is too different from what they got from CRAN.

Do we expect maintainers to use a dev branch and have master close to the CRAN version until right before a release? We do mention gitflow in https://devguide.ropensci.org/collaboration.html

**Comment by maelle** [comment]
https://discuss.ropensci.org/t/pkgdown-website-for-released-or-dev-version-of-the-package/1919

**Comment by maelle** [comment]
Depending on the progress of the discussion above, this might get shifted to the release after next one.

**Comment by maelle** [comment]
wait a bit, since there's related work in pkgdown.

https://github.com/r-lib/pkgdown/issues/1299
https://github.com/r-lib/pkgdown/issues/1373

**Comment by maelle** [comment]
Let's revisit this if/when something gets implemented in pkgdown.
