### ISSUE TITLE
Ethics guidance

### ISSUE THREAD

**Issue by maelle** [ropensci/dev_guide#209]
(From a comment by @noamross, with links added by me)

packages that scrape need
* to comply with robots.txt/terms of service https://docs.ropensci.org/robotstxt/
* to scrape ethically through transparency, caching and throttling, either built-in or via documentation. See what https://dmi3kno.github.io/polite/ does

I'd add they should write some motivation for the scraping i.e. ensure there's no other solution to get the same data.

**Comment by maelle** [comment]
Plus in general scraping is fragile so maybe there shouldn't be packages doing that :thinking:

**Comment by mkearney** [comment]
First, I appreciate that you have listed `comply with robots.txt` as a distinct bullet point from `scrape ethically`. The two may often be in agreement, but I think the more robust solution is to follow a set of *ethical principles* instead of a plain text file.

Second, while I agree scraping *is fragile* and *should be avoided when underlying data sources are exported*, I find scraping nevertheless frequently necessary to capture or preserve information. So I hope this isn't suggesting a complete ban on web scraping libraries!

**Comment by maelle** [comment]
Thanks! Do you think the PR captures that?

**Comment by mkearney** [comment]
Yes!
