### ISSUE TITLE
Guidance on acceptable LICENSEs

### ISSUE THREAD

**Issue by annakrystalli** [ropensci/dev_guide#279]
Maybe I missed it (although I did serach our dev guide) but there is nowhere obvious in the Packaging Guide nor the Edito's or Reviewers guidelines giving detail about what type of licenses are acceptable. 

The only place I see some form of definition is in the editors.md checklist where editors are asked to check:
```
- [ ] **License:** The package has a CRAN or OSI accepted license
```

Perhaps it would be a good idea to mention licensing more explicitly in the Packaging Guide (and perhaps a short ref in the Editor's guidelines) and include either a list of or links to lists of acceptable LICENSEs?

**Comment by maelle** [comment]
Good point. Do you think a link to https://r-pkgs.org/license.html would be sufficient?

**Comment by annakrystalli** [comment]
That looks like a good source of general info on LICENSEs. Perhaps though because we do specify ` CRAN or OSI accepted license` we should have a link to a list of such licences?

**Comment by maelle** [comment]
or a link to what CRAN and OSI accept? Otherwise it'd be a bit long (and could easily get out-of-sync).

* CRAN https://svn.r-project.org/R/trunk/share/licenses/license.db found via https://cran.r-project.org/web/packages/policies.html
* OSI https://opensource.org/licenses

And then the R packages book link "for more information"?

**Comment by annakrystalli** [comment]
Yes exactly! Perfect! 💯
