### ISSUE TITLE
governance.md, support.md, roadmap

### ISSUE THREAD

**Issue by maelle** [ropensci/dev_guide#289]
cc @Bisaloo 

In the chapter about making a package collaboration friendly, mention the possibility to add support.md (link to discuss.ropensci.org in a default one for the org?), governance.md, settings of the repo e.g. making a review compulsory on every PR.

Regarding a roadmap, in practice it might mean using
* GitHub issue labels with a clear indication of where help is needed. Current guidance on labelling https://devguide.ropensci.org/collaboration.html#issue-labelling
* GitHub milestones
* GitHub pinned issues
* GitHub projects (less useful I think for things that are within a single repo?)

**Comment by maelle** [comment]
* badge or something indicating how welcome contributions are? does something like that even exists?!

**Comment by Bisaloo** [comment]
>     * badge or something indicating how welcome contributions are? does something like that even exists?!

I like this idea. Sometimes, I reluctant to submit PR to fix typos when I don't know the maintainer because I'm afraid they will find that I'm wasting their time with something insignificant.

A way to signal that even typo fixes are welcome would be nice (without having to read a possibly lengthy contribution guide)

**Comment by Bisaloo** [comment]
On a related note, this makes me realise that I tend to not 100% trust very generic contributing guides. It makes me think "okay, the maintainer may have put this without really paying attention (copy/pasting usethis instructions) / because someone else required this from them. I'm not sure they really welcome contributions."

But I might be once again overcomplicating/overthinking things for no valid reason :thinking:

And this might belong to another issue as well

**Comment by maelle** [comment]
I would think typo fixes are nearly always ok because easy to merge? I make a lot of them 🤔

Agree reg generic guides. So maybe at least the text linking to it should feel less generic?

**Comment by maelle** [comment]
Reg badges there are badges indicating newbies are welcome

* https://www.firsttimersonly.com/
* http://makeapullrequest.com/

**Comment by maelle** [comment]
I was also thinking that I've recently made a fairly minimal PR to a package (using roxygen2 @inheritParams to remove docs dups) to "test the waters", I even explicitly asked in the PR whether contributions were welcome.

**Comment by maelle** [comment]
https://github.com/ropensci/opencage/pull/128#issuecomment-776834833

**Comment by maelle** [comment]
Work on this after https://ropensci.org/commcalls/apr2021-pkg-community/

**Comment by maelle** [comment]
So the next dev guide release would be in May.
