### ISSUE TITLE
Improve archival guidance (rename README, have super small README)

### ISSUE THREAD

**Issue by maelle** [ropensci/dev_guide#438]
Idea by @joelnitta

**Comment by joelnitta** [comment]
I noticed this after I subconsciously managed to skip past the "archived" labels and "Please see this package instead" disclaimers at the top of a github README and go straight to the examples to try and figure out how I could use it. It took me a while to realize that the package wasn't being actively maintained. I would guess I'm not the only one to do this!

So I think it may be a good idea to to drastically reduce the content of READMEs of archived repos so that it doesn’t appear that they are actively maintained… I’m not saying the information should not be available at all, just move it to a different document so one isn’t tempted to skip down to the examples right away.

Here are two examples for comparison:
- minimal readme (https://github.com/ropensci-archive/monkeylearn)
- "normal" readme (https://github.com/ropensci-archive/umapr)

**Comment by maelle** [comment]
Thank you!

So the TODOs here are

- improve guidance,
- fix READMEs of currently archived packages.

**Comment by joelnitta** [comment]
Yes, assuming this should become general ROpenSci policy (I'm not sure how that's decided...)

**Comment by mpadge** [comment]
I support all of these suggestions, but think that in addition to reducing all READMEs to minimal form like @joelnitta suggested, it would be good policy to suggest first copying README to, say `README-old.md`, and then to put a link in minimal README to former full version?

**Comment by mpadge** [comment]
@maelle I'm thinking the best place for this would be an additional sub-section at the end of [Chapter 15, "*Package evolution*](https://devguide.ropensci.org/evolution.html) - would you agree?

**Comment by maelle** [comment]
Yes, with a link to it in https://devguide.ropensci.org/curationpolicy.html#archivalguidance (or the other way round?)

**Comment by maelle** [comment]
noting that the link above actually has the guidance to update the README but it's vague and I haven't been consistently doing that, clearly.
