### ISSUE TITLE
Suggest using cpp role when changing package maintainers?

### ISSUE THREAD

**Issue by maelle** [ropensci/dev_guide#473]
https://twitter.com/ma_salmon/status/1526467262919716864

**Comment by maelle** [comment]
@mpadge do you have any thoughts on this?

**Comment by mpadge** [comment]
It's not (yet?) listed as [an officially recognised role](https://stat.ethz.ch/R-manual/R-devel/library/utils/html/person.html), even though those are only "suggestions". The ["official" definition of roles](https://www.loc.gov/marc/relators/relaterm.html) also does not have "cpp". Given that, I'd say we neither can nor should suggest this (yet). Mainly and especially because if we start suggesting roles that are not defined anywhere that anybody can easily find, then where might that process lead?

**Comment by maelle** [comment]
This makes sense!
