### ISSUE TITLE
Recommend pak for package installation?

### ISSUE THREAD

**Issue by maelle** [ropensci/dev_guide#794]
https://pak.r-lib.org/

**Comment by noamross** [comment]
I don't know about this and don't see a reason to have a preference for it.. I get the benefits of pak in some situations, but package installation needs vary pretty widely by use and environment (for instance, pak and renv don't work that well together despite trying), and this is a _user_ preference rather than a developer one. I would worry if for some reason a packages leaned heavily on particular install tools or for some reasons only worked with certain ones.

**Comment by noamross** [comment]
Something we might consider is asking authors to make sure that, for compiled code, package binaries are available, be it via CRAN, BioConductor, R-Universe, or CI/self-hosted repositories.

**Comment by maelle** [comment]
Good point!

pak would be for https://devdevguide.netlify.app/softwarereview_reviewer#preparereview

**Comment by mpadge** [comment]
I agree with Noam here - pak is only one way, and i think recommending that in any way would be too restrictive, so i'd suggest closing this issue.

**Comment by maelle** [comment]
R-universe is already mentioned in https://devdevguide.netlify.app/pkg_building#readme

I'll make a PR, but other occurrences of remotes.
