### ISSUE TITLE
Semantic versioning, release schedule and release notes

### ISSUE THREAD

**Issue by noamross** [ropensci/dev_guide#82]
We tend to make lots of changes to the dev guide in response to new situations and feedback, and this is good.  However, it means our standards can be something of a moving target, and it's not easy for people to see what is changed.  I propose we move to a system of dev guide "releases" on a regular schedule, similar to R packages.   We would probably merge changes no more frequently than quarterly.    

We would limit our changes and PRs to a development branch, get OK to merge the branch from the editorial board, and have a NEWS chapter that describes changes. Typos and such could be applied as hotfixes, but changes to guidelines, policies, scope, etc., and rewording/reorganization would be applied in batches.  

This would help authors see what may have changed since their last submission, and provide a regular schedule to push awareness our of those changes out via all our channels.  (blog post/tech note, slack message, tweet, etc.) We could even ping the community via Slack _prior_ to release so as to get more broad feedback on and awareness of changes. 

A little complementary idea would be to have "history" link as a header in the dev_guide, much like edit/github links, that takes you straight to the chapter's commit history.

**Comment by maelle** [comment]
👌👏

**Comment by maelle** [comment]
I need to find out how to have two versions online: I'd like to have the dev version built as well, with a link that'd be a bit more hidden.

**Comment by maelle** [comment]
I've implemented @noamross's excellent ideas minus the history button that's tackled in #85.

* NEWS file created.

* There's now a dev branch that gets deployed to dev-site that is published on Netlify so we can see how the dev_guide in development looks like. The idea would be small fixes to master (deployed to https://ropensci.github.io/dev_guide/ via gh-pages); larger fixes directly or via PRs to dev (deployed to https://devdevguide.netlify.com/ via dev-site)

* README updated.

What we now need is 

* all @ropensci/editors having a look at the README to tell me what's unclear. :-)

* Do we need some sort of banner/warning on https://devdevguide.netlify.com/ ? Not sure how, technically. And maybe not needed since we'd always link to the current accepted version at https://ropensci.github.io/dev_guide/

* a first release... after feedback from @karthik?

**Comment by noamross** [comment]
Can we make the NEWS file a chapter in the guide itself?

**Comment by maelle** [comment]
😮  as Appendix linked from the intro?

**Comment by noamross** [comment]
👍 Yes, that makes sense

**Comment by maelle** [comment]
@noamross I made the edit to master (we're still pre-first-release anyway :angel:). The wording in the intro is not very good I think.

**Comment by noamross** [comment]
I merged changes from master into dev and pushed some small language changes.

One note is that I suspect we'll get PRs into `master` when we want them in `dev`.  I was googling around for a solution to this and there are basically two: make `dev` the default branch, or treat `master` like a dev branch and have deployment go from a branch with a name like `deploy` or `stable`. I suggest making `dev` the default branch.

**Comment by maelle** [comment]
Thanks and ok!

**Comment by maelle** [comment]
Although we do want typo prs to master... i think I was hoping external contributors would open _issues_ for bigger suggestions.

**Comment by maelle** [comment]
We should moreover PR your edits to `master` before the 1st official release, right?
